Vagrant.configure("2") do |config|
  config.vm.provider "virtualbox" do |v|
    v.gui = false
  end

  config.vm.define "attacker", primary: true do |attacker|
    attacker.vm.box = "kali2024"
    attacker.vm.network "private_network", ip: "{{ attacker['ip'] }}"
    attacker.vm.provision "proxy", type: "shell", privileged: true, inline:<<-SHELL
    apt-get install -y squid
    echo -e "http_access allow localhost\nhttp_access allow localnet\nhttp_access deny all" > /etc/squid/conf.d/lan.conf
    systemctl restart squid.service
    timedatectl set-timezone Asia/Shanghai
    SHELL
    attacker.vm.provision "c2-servers", type: "shell", path: "./c2servers.sh", privileged: false
  end

  {% for vm, vmd in victim.items() if vmd.platform == 'linux' %}
  config.vm.define "{{ vm }}" do |{{ vm }}|
    {{ vm }}.vm.box = "ubuntu/trusty64"
    {{ vm }}.vm.network "private_network", ip: "{{ vmd.ip }}"
    {{ vm }}.vm.provision "{{ vm }}", type: "shell", path: "./beacon.sh", args: "{{ vmd.beacon_file }}", privileged: false
  end
  {%- endfor %}

  {% for vm, vmd in victim.items() if vmd.platform == 'windows' %}
  config.vm.define "{{ vm }}" do |{{ vm }}|
    {{ vm }}.vm.box = "stegru/win10-build"
    {{ vm }}.vm.network "private_network", ip: "{{ vmd.ip }}"
    {{ vm }}.vm.guest = :windows
    {{ vm }}.vm.communicator = "winrm"
    {{ vm }}.vm.provision "{{ vm }}", type: "shell", path: "./beacon.ps1", args: "{{ vmd.beacon_file }}", privileged: true
  end
  {%- endfor %}

  config.vm.define "benign" do |benign|
    benign.vm.box = "ubuntu/trusty64"
    benign.vm.network "private_network", ip: "{{ benign.ip }}"
    benign.vm.provision "benign", type: "shell", path: "./benign.sh", privileged: false
  end
end

