#!/bin/bash

vagrant destroy -f
rm -rf data; mkdir data

../script_generator attacker_provision.templ range.yml > data/attacker_provision
../script_generator victim_provision.ps1.templ range.yml > data/victim_provision.ps1
echo Provision scripts generated!

vagrant up
sleep 20
vagrant ssh attacker -c 'tmux new-window -t collector -n commands "cd Cobaltstrike-4.4 && ./agscript 192.168.56.33 50050 black 456321 /vagrant/commands.cna"'
echo C2 commands executed!
