Vagrant.configure("2") do |config|
  config.vm.provider "virtualbox" do |v|
    v.gui = false
  end

  config.vm.define "attacker", primary: true do |attacker|
    attacker.vm.box = "kali2024"
    attacker.vm.network "private_network", ip: "192.168.56.33"
    attacker.vm.provision "proxy", type: "shell", privileged: true, inline:<<-SHELL
    apt-get install -y squid
    echo -e "http_access allow localhost\nhttp_access allow localnet\nhttp_access deny all" > /etc/squid/conf.d/lan.conf
    systemctl restart squid.service
    timedatectl set-timezone Asia/Shanghai
    SHELL
    attacker.vm.provision "team-server", type: "shell", path: "data/attacker_provision", privileged: false
  end

  config.vm.define "victim" do |victim|
    victim.vm.box = "stegru/win10-build"
    victim.vm.network "private_network", ip: "192.168.56.44"
    victim.vm.guest = :windows
    victim.vm.communicator = "winrm"
    victim.vm.provision "victim", type: "shell", path: "data/victim_provision.ps1", privileged: true
  end

  config.vm.define "vic2" do |vic2|
    vic2.vm.box = "stegru/win10-build"
    vic2.vm.network "private_network", ip: "192.168.56.55"
    vic2.vm.guest = :windows
    vic2.vm.communicator = "winrm"
    vic2.vm.provision "vic2", type: "shell", path: "data/victim_provision.ps1", privileged: true
  end
end
