Vagrant.configure("2") do |config|
  config.vm.provider "virtualbox" do |v|
    v.gui = false
  end

  config.vm.define "attacker", primary: true do |attacker|
    attacker.vm.box = "kali2024"
    attacker.vm.network "private_network", ip: "192.168.56.33"
    attacker.vm.provision "team-server", type: "shell", path: "data/attacker_provision", privileged: false
  end

  config.vm.define "victim" do |victim|
    victim.vm.box = "baunegaard/win10pro-en"
    victim.vm.network "private_network", ip: "192.168.56.44"
    victim.vm.guest = :windows
    victim.vm.communicator = "winrm"
    victim.vm.provision "victim", type: "shell", path: "data/victim_provision.ps1", privileged: true
  end
end
